	
 -- PROFICIENCY_SPAN
WITH FIRST_STAGE (CONSTITUENT_LEARNING_STD_ID, LEARNING_STANDARD_ID, SIH_COURSEPK_ID) AS (
		SELECT DISTINCT lsh.CONSTITUENT_LEARNING_STD_ID, lsh.LEARNING_STANDARD_ID, clsm.SIH_COURSEPK_ID
		FROM IBMSIH.COURSE_LEARNING_STD_MAP clsm
		JOIN IBMSIH.SIHLEARNING_STANDARD_HIERARCHY lsh ON lsh.LEARNING_STANDARD_ID = clsm.LEARNING_STANDARD_ID
		JOIN IBMSIH.SIHLEARNING_STANDARD std ON std.LEARNING_STANDARD_ID = clsm.LEARNING_STANDARD_ID
		JOIN IBMSIH.SIHSTANDARD_CONTENT std_cont ON std_cont.STANDARD_CONTENT_ID = std.STANDARD_CONTENT_ID
		WHERE lsh.GRAPH_TYPE IN ('PROGRESSION', 'UNPACKED')
			AND clsm.TENANT_ID = :tenant_id 
		ORDER BY lsh.CONSTITUENT_LEARNING_STD_ID, lsh.LEARNING_STANDARD_ID),
	SECOND_STAGE  (CONSTITUENT_LEARNING_STD_ID, LEARNING_STANDARD_ID, SIH_COURSEPK_ID) AS (
		SELECT DISTINCT prog.CONSTITUENT_LEARNING_STD_ID, prog.LEARNING_STANDARD_ID, FIRST_STAGE.SIH_COURSEPK_ID
		FROM IBMSIH.SIHLEARNING_STANDARD_HIERARCHY prog
		JOIN FIRST_STAGE ON FIRST_STAGE.CONSTITUENT_LEARNING_STD_ID = prog.LEARNING_STANDARD_ID
		WHERE prog.GRAPH_TYPE IN ('PROGRESSION', 'UNPACKED')),
	EXTEND_UP  (CONSTITUENT_LEARNING_STD_ID, LEARNING_STANDARD_ID, SIH_COURSEPK_ID) AS (
		SELECT DISTINCT prog.CONSTITUENT_LEARNING_STD_ID, prog.LEARNING_STANDARD_ID, FIRST_STAGE.SIH_COURSEPK_ID
		FROM IBMSIH.SIHLEARNING_STANDARD_HIERARCHY prog
		JOIN FIRST_STAGE ON FIRST_STAGE.CONSTITUENT_LEARNING_STD_ID = prog.CONSTITUENT_LEARNING_STD_ID
		WHERE prog.GRAPH_TYPE = 'UNPACKED' ),
	COURSE_GRAPH_EDGES (CONSTITUENT_LEARNING_STD_ID, LEARNING_STANDARD_ID, SIH_COURSEPK_ID) AS (
		SELECT * FROM SECOND_STAGE UNION
		SELECT * FROM EXTEND_UP UNION
		SELECT * FROM FIRST_STAGE),
	COURSE_GRAPH_VERTICES (LEARNING_STANDARD_ID, SIH_COURSEPK_ID) AS (
		SELECT cge.CONSTITUENT_LEARNING_STD_ID AS LEARNING_STANDARD_ID, cge.SIH_COURSEPK_ID FROM COURSE_GRAPH_EDGES cge UNION
		SELECT cge.LEARNING_STANDARD_ID, cge.SIH_COURSEPK_ID FROM COURSE_GRAPH_EDGES cge),
	GRAPH_VERTS_SINGLETONS (LEARNING_STANDARD_ID, SIH_COURSEPK_ID) AS (
		SELECT verts.LEARNING_STANDARD_ID, verts.SIH_COURSEPK_ID FROM COURSE_GRAPH_VERTICES verts UNION
		SELECT clsm.LEARNING_STANDARD_ID, clsm.SIH_COURSEPK_ID FROM IBMSIH.COURSE_LEARNING_STD_MAP clsm
		WHERE clsm.TENANT_ID = :tenant_id),
	COURSE_SUBJECTS (SIH_COURSEPK_ID,  COURSE_SUBJECTS) AS (
		SELECT course_subj.SIH_COURSEPK_ID, 
				LISTAGG(course_subj.SUBJECT_TITLE, ', ') AS COURSE_SUBJECT
		FROM (SELECT DISTINCT verts.SIH_COURSEPK_ID, cont.SUBJECT_TITLE
			FROM GRAPH_VERTS_SINGLETONS verts
			JOIN IBMSIH.SIHLEARNING_STANDARD std ON std.LEARNING_STANDARD_ID = verts.LEARNING_STANDARD_ID
			JOIN IBMSIH.SIHSTANDARD_CONTENT cont ON cont.STANDARD_CONTENT_ID = std.STANDARD_CONTENT_ID) AS course_subj	
		GROUP BY course_subj.SIH_COURSEPK_ID
		ORDER BY course_subj.SIH_COURSEPK_ID),
	COURSE_GRADE_LVL (SIH_COURSEPK_ID, COURSE_GRADE_LVL) AS (
		SELECT course_grade.SIH_COURSEPK_ID,
				LISTAGG(course_grade.GRADE_LEVEL, ', ') AS COURSE_GRADE_LVL
		FROM (SELECT DISTINCT clsm.SIH_COURSEPK_ID, cont.GRADE_LEVEL
			FROM IBMSIH.COURSE_LEARNING_STD_MAP clsm
			JOIN IBMSIH.SIHLEARNING_STANDARD std ON std.LEARNING_STANDARD_ID = clsm.LEARNING_STANDARD_ID
			JOIN IBMSIH.SIHSTANDARD_CONTENT cont ON cont.STANDARD_CONTENT_ID = std.STANDARD_CONTENT_ID) AS course_grade
		GROUP BY course_grade.SIH_COURSEPK_ID
		ORDER BY course_grade.SIH_COURSEPK_ID),
	COURSE_ENROLLEES (SIH_COURSEPK_ID, SIH_PERSONPK_ID) AS (
		SELECT DISTINCT crs.SIH_COURSEPK_ID, opr.SIH_PERSONPK_ID
		FROM IBMSIH.SIHCOURSE crs
		JOIN (SELECT sec.SIH_COURSEPK_ID, sec.COURSE_SECTION_SID, sec.COURSE_SECTION_TITLE,
							sec_day.TERM_START_DATE, sec_day.TERM_END_DATE, sec.SIH_ORGPK_ID
					FROM IBMSIH.COURSE_SECTION sec
					JOIN (SELECT sec_day.COURSE_SECTION_SID, 
								MIN(sec_day.COURSE_SECTION_DAY_DATE) AS TERM_START_DATE,
								MAX(sec_day.COURSE_SECTION_DAY_DATE) AS TERM_END_DATE
							FROM IBMSIH.COURSE_SECTION_DAY sec_day
							GROUP BY sec_day.COURSE_SECTION_SID
							ORDER BY sec_day.COURSE_SECTION_SID) 
										AS sec_day ON sec_day.COURSE_SECTION_SID = sec.COURSE_SECTION_SID
					WHERE sec.IS_ACTIVE_YN = 1
						AND sec_day.TERM_START_DATE < CURRENT_TIMESTAMP
						AND sec_day.TERM_END_DATE > CURRENT_TIMESTAMP
					ORDER BY sec.SIH_ORGPK_ID, sec.SIH_COURSEPK_ID, sec.COURSE_SECTION_SID ) 
								AS sec ON sec.SIH_COURSEPK_ID = crs.SIH_COURSEPK_ID
		JOIN (SELECT sec_stud.COURSE_SECTION_SID, sec_stud.SIH_ORG_PERSON_ROLEPK_ID, sec_stud.IS_ACTIVE_YN
				FROM IBMSIH.COURSE_SECTION_STUDENT sec_stud
				ORDER BY sec_stud.COURSE_SECTION_SID, sec_stud.SIH_ORG_PERSON_ROLEPK_ID) 
					AS sec_stud ON sec_stud.COURSE_SECTION_SID = sec.COURSE_SECTION_SID
		JOIN IBMSIH.SIHORGPERSONROLE opr ON opr.SIH_ORG_PERSON_ROLEPK_ID = sec_stud.SIH_ORG_PERSON_ROLEPK_ID
			AND sec_stud.IS_ACTIVE_YN = '1'
			AND crs.TENANT_ID = :tenant_id
		ORDER BY crs.SIH_COURSEPK_ID, opr.SIH_PERSONPK_ID)
SELECT org.NAME AS CAMPUS, course_subj.COURSE_SUBJECTS, course_grade.COURSE_GRADE_LVL, 
		course.COURSE_ID, course.COURSE_TITLE, sec.COURSE_SECTION_TITLE, 
		pers_staff.LAST_NAME AS TEACHER_LNAME, pers_staff.FIRST_NAME AS TEACHER_FNAME,
		acad.GRADE_ENROLLED,  pers_stud.PERSON_ID AS STUDENT_ID,
		pers_stud.LAST_NAME AS STUDENT_LNAME, PERS_stud.FIRST_NAME AS STUDENT_FNAME,
		cont.SUBJECT_TITLE AS STANDARD_SUBJ, cont.GRADE_LEVEL AS STANDARD_GRADE_LVL,
		std.LEARNING_STANDARD_CD, 
		(CASE WHEN clsm.COURSE_LEARNING_STD_MAP_SID IS NULL THEN 'N'
				ELSE 'Y' END) AS BLUEPRINT_ALGNED_LRN_STD,
		'Y' AS PROG_ALGNED_LRN_STD,
		verts.LEARNING_STANDARD_ID, enrollees.SIH_COURSEPK_ID, sec.COURSE_SECTION_SID
FROM COURSE_ENROLLEES enrollees
JOIN (SELECT verts.SIH_COURSEPK_ID, verts.LEARNING_STANDARD_ID
		FROM GRAPH_VERTS_SINGLETONS verts
		ORDER BY verts.SIH_COURSEPK_ID, verts.LEARNING_STANDARD_ID)
				AS verts ON verts.SIH_COURSEPK_ID = enrollees.SIH_COURSEPK_ID
JOIN IBMSIH.SIHORGPERSONROLE opr_stud ON opr_stud.SIH_PERSONPK_ID = enrollees.SIH_PERSONPK_ID
JOIN IBMSIH.SIHLEARNING_STANDARD std ON std.LEARNING_STANDARD_ID = verts.LEARNING_STANDARD_ID
JOIN IBMSIH.SIHSTANDARD_CONTENT cont ON cont.STANDARD_CONTENT_ID = std.STANDARD_CONTENT_ID
JOIN IBMSIH.SIHCOURSE course ON course.SIH_COURSEPK_ID = enrollees.SIH_COURSEPK_ID
JOIN IBMSIH.COURSE_SECTION sec ON sec.SIH_COURSEPK_ID = enrollees.SIH_COURSEPK_ID
JOIN IBMSIH.COURSE_SECTION_STUDENT sec_stud ON sec_stud.COURSE_SECTION_SID = sec.COURSE_SECTION_SID
											AND sec_stud.SIH_ORG_PERSON_ROLEPK_ID = opr_stud.SIH_ORG_PERSON_ROLEPK_ID
JOIN IBMSIH.COURSE_SECTION_STAFF sec_staff ON sec_staff.COURSE_SECTION_SID = sec.COURSE_SECTION_SID
JOIN IBMSIH.SIHORGPERSONROLE opr_staff ON opr_staff.SIH_ORG_PERSON_ROLEPK_ID = sec_staff.SIH_ORG_PERSON_ROLEPK_ID
JOIN IBMSIH.SIHPERSON pers_staff ON pers_staff.SIH_PERSONPK_ID = opr_staff.SIH_PERSONPK_ID
JOIN IBMSIH.SIHPERSON pers_stud ON pers_stud.SIH_PERSONPK_ID = opr_stud.SIH_PERSONPK_ID
JOIN IBMSIH.SIHORG org ON org.SIH_ORGPK_ID = sec.SIH_ORGPK_ID
JOIN COURSE_GRADE_LVL course_grade ON course_grade.SIH_COURSEPK_ID = enrollees.SIH_COURSEPK_ID
JOIN COURSE_SUBJECTS course_subj ON course_subj.SIH_COURSEPK_ID = enrollees.SIH_COURSEPK_ID
JOIN (SELECT acad.SIH_ORG_PERSON_ROLEPK_ID_ST AS SIH_ORG_PERSON_ROLEPK_ID, acad.GRADE_ENROLLED
		FROM IBMSIH.SIHK12ACADRECORD acad
		JOIN IBMSIH.ACADEMIC_YEAR_LOOKUP acad_yr ON acad_yr.ACADEMIC_YEAR = acad.SCHOOL_YEAR
		WHERE acad_yr.ACADEMIC_YEAR_START < CURRENT_TIMESTAMP
			AND acad_yr.ACADMEMIC_YEAR_END > CURRENT_TIMESTAMP)
				AS acad ON acad.SIH_ORG_PERSON_ROLEPK_ID = opr_stud.SIH_ORG_PERSON_ROLEPK_ID
LEFT JOIN ( SELECT DISTINCT clsm.SIH_COURSEPK_ID, clsm.LEARNING_STANDARD_ID, clsm.COURSE_LEARNING_STD_MAP_SID
			FROM IBMSIH.COURSE_LEARNING_STD_MAP clsm 
			ORDER BY clsm.SIH_COURSEPK_ID, clsm.LEARNING_STANDARD_ID) 
									AS clsm ON clsm.SIH_COURSEPK_ID = enrollees.SIH_COURSEPK_ID
											AND clsm.LEARNING_STANDARD_ID = verts.LEARNING_STANDARD_ID
ORDER BY enrollees.SIH_COURSEPK_ID, pers_stud.PERSON_ID, sec.COURSE_SECTION_SID, verts.LEARNING_STANDARD_ID