SELECT DISTINCT course.SIH_COURSEPK_ID, course.COURSE_ID, course.COURSE_TITLE
FROM IBMSIH.SIHCOURSE course 
JOIN (SELECT sec.SIH_COURSEPK_ID, sec.COURSE_SECTION_SID
	  FROM IBMSIH.COURSE_SECTION sec
	  JOIN IBMSIH.ACADEMIC_YEAR_LOOKUP acad_yr ON acad_yr.ACADEMIC_YEAR = sec.ACADEMIC_YEAR_DELIVERED
	  WHERE acad_yr.ACADEMIC_YEAR_START < CURRENT_TIMESTAMP
	       AND acad_yr.ACADMEMIC_YEAR_END > CURRENT_TIMESTAMP
	       AND sec.TENANT_ID = :tenant_id
	  ORDER BY sec.SIH_COURSEPK_ID, sec.COURSE_SECTION_SID ) 
					AS sec ON sec.SIH_COURSEPK_ID = course.SIH_COURSEPK_ID