SELECT acad_yr.ACADEMIC_YEAR, acad_yr.ACADEMIC_YEAR_START, acad_yr.ACADMEMIC_YEAR_END
FROM IBMSIH.ACADEMIC_YEAR_LOOKUP acad_yr
WHERE acad_yr.TENANT_ID = :tenant_id
	AND acad_yr.ACADEMIC_YEAR_START < CURRENT_DATE
	AND acad_yr.ACADMEMIC_YEAR_END > CURRENT_DATE