SELECT cont.SUBJECT_TITLE, cont.GRADE_LEVEL, std.LEARNING_STANDARD_ID, 
		std.LEARNING_STANDARD_CD, std.MEASUREABLE_STANDARD_YN,
		std.LEARNING_STANDARD_TITLE
FROM IBMSIH.SIHLEARNING_STANDARD std
JOIN IBMSIH.SIHSTANDARD_CONTENT cont ON cont.STANDARD_CONTENT_ID = std.STANDARD_CONTENT_ID
WHERE std.JURISDICTION_ID = :juris_id